[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ['GeneralisedIncentives/=lib/GeneralisedIncentives/']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
